CC=gcc
CFLAGS=-Wall -Wextra -Werror 
NAME=libft.a
OBJECTS=*.o
FILES= libft.h ft_isprint.c ft_memset.c ft_strchr.c ft_strnstr.c ft_atoi.c ft_itoa.c ft_putchar_fd.c ft_strdup.c ft_strrchr.c
ft_bzero.c ft_putendl_fd.c  ft_striteri.c  ft_strtrim.c ft_calloc.c ft_memchr.c ft_putnbr_fd.c ft_strjoin.c ft_substr.c
ft_isalnum.c ft_putstr_fd.c ft_strlcat.c ft_tolower.c ft_isalpha.c ft_memcmp.c ft_split	ft_strlcpy.c ft_toupper.c
ft_isascii.c ft_memcpy.c ft_split.c ft_strlen.c ft_isdigit.c ft_memmove.c ft_stmapi.c ft_strncmp.c

all:

	$(CC) $(CFLAGS) $(NAME) $(FILES)

$(NAME):

bonus:
 
clean:

fclean: 
	
re: